kind: ConfigMap
apiVersion: v1
metadata:
  name: web-config
data:
  config.json: >
    {"masterFileUrl":"http://caj-gateway-{{ .Values.targetNamespace }}.{{ .Values.domain }}","fareUrl":"http://caj-gateway-{{ .Values.targetNamespace }}.{{ .Values.domain }}","scheduleUrl":"http://caj-gateway-{{ .Values.targetNamespace }}.{{ .Values.domain }}"}
