kind: Deployment
apiVersion: apps/v1
metadata:
  name: caj-web
  labels:
    app: caj-web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caj-web
      version: v1
  template:
    metadata:
      labels:
        app: caj-web
        version: v1
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: web-config
            defaultMode: 420
      containers:
        - name: caj-web
          image: "{{ .Values.image.repository }}/caj-web:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /opt/app-root/src/assets/config.json
              subPath: config.json
          ports:
            - containerPort: 8080
              protocol: TCP