kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: caj-web
spec:
  host: "caj-web-{{ .Values.targetNamespace }}.{{ .Values.domain }}"
  to:
    kind: Service
    name: caj-web
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None