FROM registry.access.redhat.com/ubi8/openjdk-11:latest
ENV APP_HOME=/home/jboss APP_NAME=schedule
EXPOSE 8080
WORKDIR ${APP_HOME}
COPY ./build/libs/${APP_NAME}-0.0.1-SNAPSHOT.jar ./app.jar
COPY ../otel-agent/opentelemetry-javaagent.jar ./opentelemetry-javaagent.jar
USER root
RUN cp  && \
    chown jboss:root ${APP_HOME} && \
    chmod -R 755 ${APP_HOME}/*.jar
USER boss
CMD [ "java","-Dotel.exporter=jaeger","-Dotel.exporter.jaeger.endpoint=jaeger-collector.istio-system.svc.cluster.local:14250","-Dotel.exporter.jaeger.service.name=schedule","-Dotel.resource.attributes=service.name=schedule","-javaagent:opentelemetry-javaagent.jar","-jar","app.jar" ]