kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: caj-master-file
spec:
  host: "caj-master-file-{{ .Values.targetNamespace }}.{{ .Values.domain }}"
  to:
    kind: Service
    name: caj-master-file
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None