kind: Service
apiVersion: v1
metadata:
  name: caj-master-file
  labels:
    app: caj-master-file
    service: caj-master-file
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: caj-master-file