spring:
  application:
    name: gateway  
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
      routes:
      - id: master-file
        uri: ${MASTER_FILE_URI:http://127.0.0.1:8081}
        predicates:
        - Path=/api/master-files/**
      - id: fare
        uri: ${FARE_URI:http://127.0.0.1:8082}
        predicates:
        - Path=/api/fare/**
      - id: schedule
        uri: ${SCHEDULE_URI:http://127.0.0.1:8083}
        predicates:
        - Path=/api/schedule/**
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: ${JAEGER_URI:http://jaeger-collector.istio-system.svc.cluster.local:4317}
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - prometheus     