global:
  resolve_timeout: 5m
  slack_api_url: >-
    https://xxxx
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
receivers:
  - name: Critical
  - name: Default
  - name: slack
    slack_configs:
      - channel: '#ocp4-alert'
        text: |-
          <!channel> 
          summary: {{ .CommonAnnotations.summary }}
        http_config:
          proxy_url: 'http://xxxx:3128'
  - name: Watchdog
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 1m
  routes:
    - matchers:
        - alertname = Watchdog
      receiver: Watchdog
    - matchers:
        - severity = critical
      receiver: Critical
    - receiver: slack
      match_re:
        severity: Warning|Critical