apiVersion: v1
baseDomain: rhtw.kubedev.org
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: otter
networking:
  clusterNetworks:
  - cidr: 10.131.0.0/16
    hostPrefix: 24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.31.0.0/16
platform:
  none: {}
proxy:
  httpProxy: http://proxy.otter.rhtw.kubedev.org:3128 
  httpsProxy: http://proxy.otter.rhtw.kubedev.org:3128 
  noProxy: otter.rhtw.kubedev.org,rhtw.kubedev.org,192.168.101.0/24,10.131.0.0/16,172.31.0.0/16
pullSecret: '${PULL_SECRET}' 
sshKey: '${SSH_KEY}'