apiVersion: v1
baseDomain: lab.exmaple.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: caj
networking:
  clusterNetworks:
  - cidr: 10.131.0.0/16
    hostPrefix: 24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.31.0.0/16
platform:
  none: {}
pullSecret: '${PULL_SECRET}' 
sshKey: '${SSH_KEY}'