apiVersion: v1
kind: Pod
metadata:
  namespace: devops-system
spec:
  serviceAccountName: "jenkins"
  containers:
  - name: nodejs
    image: registry.access.redhat.com/ubi8/nodejs-14:1-93
    imagePullPolicy: Always
    env:
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/tmp"
    - name: http_proxy
      value: 'http://proxy.penguin.rhtw.kubedev.org:3128'
    - name: https_proxy
      value: 'http://proxy.penguin.rhtw.kubedev.org:3128'
    - name: no_proxy
      value: '127.0.0.1,localhost,.cluster.local,.svc,10.0.0.0/16,10.130.0.0/16,127.0.0.1,172.30.0.0/16,192.168.100.0/24,api-int.penguin.rhtw.kubedev.org,localhost,penguin.rhtw.kubedev.org,rhtw.kubedev.org'
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    resources:
      limits:
        memory: "1Gi"
        cpu: "1000m"
      requests:
        memory: "500Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: "/tmp"
      name: workspace-volume
      readOnly: false
    - mountPath: "/home/jenkins/.npm"
      name: nodejs-cache
      readOnly: false
  - name: podman
    image: registry.redhat.io/rhel8/podman:8.7
    imagePullPolicy: Always
    env:
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/tmp"
    - name: http_proxy
      value: 'http://proxy.penguin.rhtw.kubedev.org:3128'
    - name: https_proxy
      value: 'http://proxy.penguin.rhtw.kubedev.org:3128'
    - name: no_proxy
      value: '127.0.0.1,localhost,.cluster.local,.svc,10.0.0.0/16,10.130.0.0/16,127.0.0.1,172.30.0.0/16,192.168.100.0/24,api-int.penguin.rhtw.kubedev.org,localhost,penguin.rhtw.kubedev.org,rhtw.kubedev.org'
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
      requests:
        memory: "250Mi"
        cpu: "100m"
    volumeMounts:
    - mountPath: "/tmp"
      name: workspace-volume
      readOnly: false
  - name: ose-cli
    image: registry.redhat.io/openshift4/ose-cli:v4.10
    imagePullPolicy: Always
    env:
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/tmp"
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    resources:
      limits:
        memory: "250Mi"
        cpu: "250m"
      requests:
        memory: "100Mi"
        cpu: "50m"
    volumeMounts:
    - mountPath: "/tmp"
      name: workspace-volume
      readOnly: false
    workingDir: "/tmp"
  volumes:
  - emptyDir:
      medium: ""
    name: workspace-volume
  - name: nodejs-cache
    persistentVolumeClaim:
      claimName: jenkins-cache-pvc