FROM registry.access.redhat.com/ubi8/openjdk-11:1.14-5
USER root
COPY . .
RUN chown -R jboss:root /home/jboss
USER jboss
RUN ./gradlew clean && ./gradlew build
CMD java -Djava.net.preferIPv4Stack=true -jar /home/jboss/build/libs/master-file-0.0.1-SNAPSHOT.jar