FROM registry.access.redhat.com/ubi8/openjdk-11:1.14-5

COPY ./build/libs/master-file-0.0.1-SNAPSHOT.jar /home/jboss/app.jar

USER root

RUN chown jboss:root /home/jboss && \
    chmod -R 755 /home/jboss/app.jar

USER jboss

CMD java -Djava.net.preferIPv4Stack=true -jar /home/jboss/app.jar
