FROM dorowu/ubuntu-desktop-lxde-vnc:latest
RUN wget -c https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.10/openshift-client-linux.tar.gz -O - | tar -xz && mv kubectl /usr/local/bin/ && mv oc /usr/local/bin/

