FROM registry.access.redhat.com/ubi8/openjdk-11:latest

EXPOSE 8080

WORKDIR /home/jboss

COPY ./build/libs/fare-0.0.1-SNAPSHOT.jar ./app.jar

USER root

RUN chown jboss:root /home/jboss && \
    chmod -R 755 /home/jboss/app.jar

USER jboss

CMD [ "java","-jar","app.jar" ]