FROM registry.access.redhat.com/ubi8/openjdk-11:latest
EXPOSE 8080
WORKDIR /home/jboss
USER root
COPY . .
RUN chown -R jboss:root /home/jboss
USER jboss
RUN ./gradlew \
-Dhttps.proxyHost=proxy.penguin.rhtw.kubedev.org  \
-Dhttps.proxyPort=3128 \
-Dhttp.proxyHost=proxy.penguin.rhtw.kubedev.org \
-Dhttp.proxyPort=3128 \
&& ./gradlew build \
-Dhttps.proxyHost=proxy.penguin.rhtw.kubedev.org  \
-Dhttps.proxyPort=3128 \
-Dhttp.proxyHost=proxy.penguin.rhtw.kubedev.org \
-Dhttp.proxyPort=3128 
CMD [ "java","-jar","app.jar" ]