kind: ConfigMap
apiVersion: v1
metadata:
  name: web-config
data:
  config.json: >
    {"masterFileUrl":"http://caj-master-file-speaker01.apps.penguin.rhtw.kubedev.org","fareUrl":"http://caj-fare-speaker01.apps.penguin.rhtw.kubedev.org","scheduleUrl":"http://caj-schedule-speaker01.apps.penguin.rhtw.kubedev.org"}