INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('1','NAK',10,'Nankang','南港','1');
INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('2','TPE',20,'Taipei','台北','2');
INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('3','BAC',30,'Banqiao','板橋','3');
INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('4','TAY',50,'Taoyuan','桃園','4');
INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('5','HSC',50,'Hsinchu','新竹','5');
INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('6','MIL',50,'Miaoli','苗栗','6');
INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('7','TAC',50,'Taichung','台中','7');
INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('8','CHA',50,'Changhua','彰化','8');
INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('9','YUL',50,'Yunlin','雲林','9');
INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('10','CHY',50,'Chiayi','嘉義','10');
INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('11','TAN',50,'Tainan','台南','11');
INSERT INTO STATION(STATION_ID,STATION_CODE,STATION_DISTANCE,STATION_ENG_NAME,STATION_NAME,STATION_ORDER) VALUES ('12','ZUY',50,'Zuoying','左營','12');

INSERT INTO STOPPING_PATTERN(STOPPING_PATTERN_ID,STOPPING_PATTERN_NAME,STOPPING_PATTERN_DETAIL) VALUES ('A','直達','1,2,3,7,12'); 
INSERT INTO STOPPING_PATTERN(STOPPING_PATTERN_ID,STOPPING_PATTERN_NAME,STOPPING_PATTERN_DETAIL) VALUES ('B','跳蛙式','1,2,3,7,8,9,10,11,12'); 
INSERT INTO STOPPING_PATTERN(STOPPING_PATTERN_ID,STOPPING_PATTERN_NAME,STOPPING_PATTERN_DETAIL) VALUES ('C','站站停','1,2,3,4,5,6,7,8,9,10,11,12'); 