kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${STUDENT_ID}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: ${STUDENT_ID}-pv
  volumeMode: Filesystem