kind: Deployment
apiVersion: apps/v1
metadata:
  name: caj-schedule
  labels:
    app: caj-schedule
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caj-schedule
      version: v1
  template:
    metadata:
      labels:
        app: caj-schedule
        version: v1
    spec:
      containers:
        - name: caj-schedule
          image: "{{ .Values.image.repository }}/caj-schedule:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP