kind: Service
apiVersion: v1
metadata:
  name: caj-schedule
  labels:
    app: caj-schedule
    service: caj-schedule
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: caj-schedule