kind: Deployment
apiVersion: apps/v1
metadata:
  name: student-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-cli
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: student-cli
    spec:
      containers:
        - resources: {}
          stdin: true
          terminationMessagePath: /dev/termination-log
          name: ose-cli
          env:
          - name: http_proxy
            value: 'http://proxy.penguin.rhtw.kubedev.org:3128'
          - name: https_proxy
            value: 'http://proxy.penguin.rhtw.kubedev.org:3128'
          - name: no_proxy
            value: 'penguin.rhtw.kubedev.org,rhtw.kubedev.org,192.168.100.0/24'
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          tty: true
          image: 'docker.io/d0ck3rj3ff/ose-cli:latest'
      restartPolicy: Always
